version: '2'

services:
  app:
    image: abakpress/ruby-app:$RUBY_IMAGE_TAG
    environment:
      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
      - BUNDLE_CONFIG=/app/.bundle/config
      - RAILS_ENV=$RAILS_ENV
    command: bash
    volumes:
      - .:/app
